
import Link from "next/link";
import "./mystyle.css";

export const metadata = {
  title: 'BMI Calculator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
